services:
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - db
    environment:
      - DATABASE_URL=postgresql://nandhu:masspassword@db:5432/visitor_db
  redis:
    image: "redis:alpine"
    ports:
      - "6379:6379"
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=nandhu
      - POSTGRES_PASSWORD=masspassword
      - POSTGRES_DB=visitor_db
    ports:
      - "5432:5432"
