name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to Server via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.AWS_HOST }}
        username: ubuntu
        key: ${{ secrets.AWS_PRIVATE_KEY }}
        script: |
          cd aws-cicd-project
          git fetch origin
          git reset --hard origin/main
          sudo apt-get update -y
          sudo apt-get install docker-compose-v2 -y
          sudo docker rm -f $(sudo docker ps -aq) || true
          sudo docker compose down || true
          sudo docker compose up -d --build
